version: '2.2'
services:
  web:
    image: base:latest
    container_name: {{web_container_name}}
    working_dir: '/web'
    volumes:
      - ./web:/web
    command: ['npm', 'run', 'dev']
    environment:
      - PATH=/root/.nvm/versions/node/v21.7.1/bin/:/bin
    network_mode: "host"
    restart: always
      
  backend:
    image: base:latest
    container_name: {{backend_container_name}}
    working_dir: '/app'
    volumes:
      - ./:/app
      - ../sdk:/sdk
    command: ['python', '-u', 'backend']
    environment:
      - PYTHONPATH=./sdk:../sdk:./:../:$PYTHONPATH
    network_mode: "host"
    restart: always
